name: dojo-genesis-desktop
version: 0.0.1
description: Mindful AI Desktop App - Local-first intelligence workbench

# Tech Stack
stack:
  backend: go
  frontend: react-vite
  database: sqlite
  webview: native

# Zenflow Automation Protocol
automation:
  setup_script: "go mod download && cd app/ui/app && npm install"
  dev_server_script: "go run cmd/dgd/main.go"
  cleanup_script: "go fmt ./... && go vet ./... && go test ./..."
  copy_files:
    - .env
    - .env.local

# Project Structure
structure:
  backend:
    - agents/supervisor
    - agents/dojo
    - agents/librarian
    - agents/builder
    - api
    - database
    - tools
  frontend:
    - app/ui/app/src/components
    - app/ui/app/src/pages
    - app/ui/app/src/lib
  docs:
    - docs/architecture
    - docs/api
    - docs/guides

# Development Phases
phases:
  - name: "Sprint 1: Supervisor Agent"
    version: 0.0.1
    duration: "3 days"
    deliverables:
      - Intent classification
      - Agent routing
      - Basic API endpoints
      - Unit tests
  
  - name: "Sprint 2: Librarian Agent"
    version: 0.0.2
    duration: "3 days"
    deliverables:
      - File search
      - Seed retrieval
      - SQLite integration
      - Unit tests
  
  - name: "Sprint 3: Builder Agent"
    version: 0.0.3
    duration: "4 days"
    deliverables:
      - Code generation
      - Safe execution sandbox
      - Docker integration
      - Unit tests
  
  - name: "Sprint 4: Dojo Agent"
    version: 0.0.4
    duration: "4 days"
    deliverables:
      - Four modes (Mirror, Scout, Gardener, Implementation)
      - Perspective handling
      - Compassionate boundaries
      - Unit tests

# Quality Standards
quality:
  test_coverage: 80
  code_style: gofmt
  linting: golangci-lint
  documentation: godoc

# Audit Schedule
audit:
  frequency: weekly
  log_file: docs/AUDIT_LOG.md
  checklist:
    - Code quality review
    - Performance profiling
    - Security scan
    - Technical debt assessment
